LVGL_PATH = lvgl

#ASRCS += $(LVGL_PATH)/src/draw/sw/blend/neon/lv_blend_neon.S
C_SOURCES += $(LVGL_PATH)/src/core/lv_group.c  \
         $(LVGL_PATH)/src/core/lv_obj.c  \
         $(LVGL_PATH)/src/core/lv_obj_class.c  \
         $(LVGL_PATH)/src/core/lv_obj_draw.c  \
         $(LVGL_PATH)/src/core/lv_obj_event.c  \
         $(LVGL_PATH)/src/core/lv_obj_id_builtin.c  \
         $(LVGL_PATH)/src/core/lv_obj_pos.c  \
         $(LVGL_PATH)/src/core/lv_obj_property.c  \
         $(LVGL_PATH)/src/core/lv_obj_scroll.c  \
         $(LVGL_PATH)/src/core/lv_obj_style.c  \
         $(LVGL_PATH)/src/core/lv_obj_style_gen.c  \
         $(LVGL_PATH)/src/core/lv_obj_tree.c  \
         $(LVGL_PATH)/src/core/lv_refr.c  \
         $(LVGL_PATH)/src/dev/display/drm/lv_linux_drm.c  \
         $(LVGL_PATH)/src/dev/display/fb/lv_linux_fbdev.c  \
         $(LVGL_PATH)/src/dev/evdev/lv_evdev.c  \
         $(LVGL_PATH)/src/dev/nuttx/lv_nuttx_entry.c  \
         $(LVGL_PATH)/src/dev/nuttx/lv_nuttx_fbdev.c  \
         $(LVGL_PATH)/src/dev/nuttx/lv_nuttx_lcd.c  \
         $(LVGL_PATH)/src/dev/nuttx/lv_nuttx_libuv.c  \
         $(LVGL_PATH)/src/dev/nuttx/lv_nuttx_touchscreen.c  \
         $(LVGL_PATH)/src/dev/sdl/lv_sdl_keyboard.c  \
         $(LVGL_PATH)/src/dev/sdl/lv_sdl_mouse.c  \
         $(LVGL_PATH)/src/dev/sdl/lv_sdl_mousewheel.c  \
         $(LVGL_PATH)/src/dev/sdl/lv_sdl_window.c  \
         $(LVGL_PATH)/src/dev/x11/lv_x11_display.c  \
         $(LVGL_PATH)/src/dev/x11/lv_x11_input.c  \
         $(LVGL_PATH)/src/display/lv_display.c  \
         $(LVGL_PATH)/src/draw/lv_draw.c  \
         $(LVGL_PATH)/src/draw/lv_draw_arc.c  \
         $(LVGL_PATH)/src/draw/lv_draw_buf.c  \
         $(LVGL_PATH)/src/draw/lv_draw_image.c  \
         $(LVGL_PATH)/src/draw/lv_draw_label.c  \
         $(LVGL_PATH)/src/draw/lv_draw_line.c  \
         $(LVGL_PATH)/src/draw/lv_draw_mask.c  \
         $(LVGL_PATH)/src/draw/lv_draw_rect.c  \
         $(LVGL_PATH)/src/draw/lv_draw_triangle.c  \
         $(LVGL_PATH)/src/draw/lv_draw_vector.c  \
         $(LVGL_PATH)/src/draw/lv_image_buf.c  \
         $(LVGL_PATH)/src/draw/lv_image_decoder.c  \
         $(LVGL_PATH)/src/draw/nxp/pxp/lv_draw_buf_pxp.c  \
         $(LVGL_PATH)/src/draw/nxp/pxp/lv_draw_pxp.c  \
         $(LVGL_PATH)/src/draw/nxp/pxp/lv_draw_pxp_bg_img.c  \
         $(LVGL_PATH)/src/draw/nxp/pxp/lv_draw_pxp_fill.c  \
         $(LVGL_PATH)/src/draw/nxp/pxp/lv_draw_pxp_img.c  \
         $(LVGL_PATH)/src/draw/nxp/pxp/lv_draw_pxp_layer.c  \
         $(LVGL_PATH)/src/draw/nxp/pxp/lv_pxp_cfg.c  \
         $(LVGL_PATH)/src/draw/nxp/pxp/lv_pxp_osa.c  \
         $(LVGL_PATH)/src/draw/nxp/pxp/lv_pxp_utils.c  \
         $(LVGL_PATH)/src/draw/nxp/vglite/lv_draw_buf_vglite.c  \
         $(LVGL_PATH)/src/draw/nxp/vglite/lv_draw_vglite.c  \
         $(LVGL_PATH)/src/draw/nxp/vglite/lv_draw_vglite_arc.c  \
         $(LVGL_PATH)/src/draw/nxp/vglite/lv_draw_vglite_bg_img.c  \
         $(LVGL_PATH)/src/draw/nxp/vglite/lv_draw_vglite_border.c  \
         $(LVGL_PATH)/src/draw/nxp/vglite/lv_draw_vglite_fill.c  \
         $(LVGL_PATH)/src/draw/nxp/vglite/lv_draw_vglite_img.c  \
         $(LVGL_PATH)/src/draw/nxp/vglite/lv_draw_vglite_label.c  \
         $(LVGL_PATH)/src/draw/nxp/vglite/lv_draw_vglite_layer.c  \
         $(LVGL_PATH)/src/draw/nxp/vglite/lv_draw_vglite_line.c  \
         $(LVGL_PATH)/src/draw/nxp/vglite/lv_vglite_buf.c  \
         $(LVGL_PATH)/src/draw/nxp/vglite/lv_vglite_matrix.c  \
         $(LVGL_PATH)/src/draw/nxp/vglite/lv_vglite_path.c  \
         $(LVGL_PATH)/src/draw/nxp/vglite/lv_vglite_utils.c  \
         $(LVGL_PATH)/src/draw/renesas/dave2d/lv_draw_dave2d.c  \
         $(LVGL_PATH)/src/draw/renesas/dave2d/lv_draw_dave2d_arc.c  \
         $(LVGL_PATH)/src/draw/renesas/dave2d/lv_draw_dave2d_border.c  \
         $(LVGL_PATH)/src/draw/renesas/dave2d/lv_draw_dave2d_fill.c  \
         $(LVGL_PATH)/src/draw/renesas/dave2d/lv_draw_dave2d_image.c  \
         $(LVGL_PATH)/src/draw/renesas/dave2d/lv_draw_dave2d_label.c  \
         $(LVGL_PATH)/src/draw/renesas/dave2d/lv_draw_dave2d_line.c  \
         $(LVGL_PATH)/src/draw/renesas/dave2d/lv_draw_dave2d_mask_rectangle.c  \
         $(LVGL_PATH)/src/draw/renesas/dave2d/lv_draw_dave2d_triangle.c  \
         $(LVGL_PATH)/src/draw/renesas/dave2d/lv_draw_dave2d_uitls.c  \
         $(LVGL_PATH)/src/draw/sdl/lv_draw_sdl.c  \
         $(LVGL_PATH)/src/draw/sw/blend/lv_draw_sw_blend.c  \
         $(LVGL_PATH)/src/draw/sw/blend/lv_draw_sw_blend_to_argb8888.c  \
         $(LVGL_PATH)/src/draw/sw/blend/lv_draw_sw_blend_to_rgb565.c  \
         $(LVGL_PATH)/src/draw/sw/blend/lv_draw_sw_blend_to_rgb888.c  \
         $(LVGL_PATH)/src/draw/sw/lv_draw_sw.c  \
         $(LVGL_PATH)/src/draw/sw/lv_draw_sw_arc.c  \
         $(LVGL_PATH)/src/draw/sw/lv_draw_sw_border.c  \
         $(LVGL_PATH)/src/draw/sw/lv_draw_sw_box_shadow.c  \
         $(LVGL_PATH)/src/draw/sw/lv_draw_sw_fill.c  \
         $(LVGL_PATH)/src/draw/sw/lv_draw_sw_gradient.c  \
         $(LVGL_PATH)/src/draw/sw/lv_draw_sw_img.c  \
         $(LVGL_PATH)/src/draw/sw/lv_draw_sw_letter.c  \
         $(LVGL_PATH)/src/draw/sw/lv_draw_sw_line.c  \
         $(LVGL_PATH)/src/draw/sw/lv_draw_sw_mask.c  \
         $(LVGL_PATH)/src/draw/sw/lv_draw_sw_mask_rect.c  \
         $(LVGL_PATH)/src/draw/sw/lv_draw_sw_transform.c  \
         $(LVGL_PATH)/src/draw/sw/lv_draw_sw_triangle.c  \
         $(LVGL_PATH)/src/draw/sw/lv_draw_sw_vector.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_draw_buf_vg_lite.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_draw_vg_lite.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_draw_vg_lite_arc.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_draw_vg_lite_border.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_draw_vg_lite_box_shadow.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_draw_vg_lite_fill.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_draw_vg_lite_img.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_draw_vg_lite_label.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_draw_vg_lite_layer.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_draw_vg_lite_line.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_draw_vg_lite_mask_rect.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_draw_vg_lite_triangle.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_draw_vg_lite_vector.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_vg_lite_decoder.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_vg_lite_math.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_vg_lite_path.c  \
         $(LVGL_PATH)/src/draw/vg_lite/lv_vg_lite_utils.c  \
         $(LVGL_PATH)/src/font/lv_binfont_loader.c  \
         $(LVGL_PATH)/src/font/lv_font.c  \
         $(LVGL_PATH)/src/font/lv_font_dejavu_16_persian_hebrew.c  \
         $(LVGL_PATH)/src/font/lv_font_fmt_txt.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_10.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_12.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_14.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_16.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_18.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_20.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_22.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_24.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_26.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_28.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_28_compressed.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_30.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_32.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_34.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_36.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_38.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_40.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_42.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_44.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_46.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_48.c  \
         $(LVGL_PATH)/src/font/lv_font_montserrat_8.c  \
         $(LVGL_PATH)/src/font/lv_font_simsun_16_cjk.c  \
         $(LVGL_PATH)/src/font/lv_font_unscii_16.c  \
         $(LVGL_PATH)/src/font/lv_font_unscii_8.c  \
         $(LVGL_PATH)/src/indev/lv_indev.c  \
         $(LVGL_PATH)/src/indev/lv_indev_scroll.c  \
         $(LVGL_PATH)/src/layouts/flex/lv_flex.c  \
         $(LVGL_PATH)/src/layouts/grid/lv_grid.c  \
         $(LVGL_PATH)/src/layouts/lv_layout.c  \
         $(LVGL_PATH)/src/libs/barcode/code128.c  \
         $(LVGL_PATH)/src/libs/barcode/lv_barcode.c  \
         $(LVGL_PATH)/src/libs/bin_decoder/lv_bin_decoder.c  \
         $(LVGL_PATH)/src/libs/bmp/lv_bmp.c  \
         $(LVGL_PATH)/src/libs/ffmpeg/lv_ffmpeg.c  \
         $(LVGL_PATH)/src/libs/freetype/lv_freetype.c  \
         $(LVGL_PATH)/src/libs/freetype/lv_freetype_image.c  \
         $(LVGL_PATH)/src/libs/freetype/lv_freetype_outline.c  \
         $(LVGL_PATH)/src/libs/freetype/lv_ftsystem.c  \
         $(LVGL_PATH)/src/libs/fsdrv/lv_fs_cbfs.c  \
         $(LVGL_PATH)/src/libs/fsdrv/lv_fs_fatfs.c  \
         $(LVGL_PATH)/src/libs/fsdrv/lv_fs_memfs.c  \
         $(LVGL_PATH)/src/libs/fsdrv/lv_fs_posix.c  \
         $(LVGL_PATH)/src/libs/fsdrv/lv_fs_stdio.c  \
         $(LVGL_PATH)/src/libs/fsdrv/lv_fs_win32.c  \
         $(LVGL_PATH)/src/libs/gif/gifdec.c  \
         $(LVGL_PATH)/src/libs/gif/lv_gif.c  \
         $(LVGL_PATH)/src/libs/libjpeg_turbo/lv_libjpeg_turbo.c  \
         $(LVGL_PATH)/src/libs/libpng/lv_libpng.c  \
         $(LVGL_PATH)/src/libs/lodepng/lodepng.c  \
         $(LVGL_PATH)/src/libs/lodepng/lv_lodepng.c  \
         $(LVGL_PATH)/src/libs/lz4/lz4.c  \
         $(LVGL_PATH)/src/libs/qrcode/lv_qrcode.c  \
         $(LVGL_PATH)/src/libs/qrcode/qrcodegen.c  \
         $(LVGL_PATH)/src/libs/rle/lv_rle.c  \
         $(LVGL_PATH)/src/libs/rlottie/lv_rlottie.c  \
         $(LVGL_PATH)/src/libs/tiny_ttf/lv_tiny_ttf.c  \
         $(LVGL_PATH)/src/libs/tjpgd/lv_tjpgd.c  \
         $(LVGL_PATH)/src/libs/tjpgd/tjpgd.c  \
         $(LVGL_PATH)/src/lv_init.c  \
         $(LVGL_PATH)/src/misc/cache/lv_cache.c  \
         $(LVGL_PATH)/src/misc/cache/lv_cache_entry.c  \
         $(LVGL_PATH)/src/misc/cache/lv_image_cache.c  \
         $(LVGL_PATH)/src/misc/cache/_lv_cache_lru_rb.c  \
         $(LVGL_PATH)/src/misc/lv_anim.c  \
         $(LVGL_PATH)/src/misc/lv_anim_timeline.c  \
         $(LVGL_PATH)/src/misc/lv_area.c  \
         $(LVGL_PATH)/src/misc/lv_array.c  \
         $(LVGL_PATH)/src/misc/lv_async.c  \
         $(LVGL_PATH)/src/misc/lv_bidi.c  \
         $(LVGL_PATH)/src/misc/lv_color.c  \
         $(LVGL_PATH)/src/misc/lv_color_op.c  \
         $(LVGL_PATH)/src/misc/lv_event.c  \
         $(LVGL_PATH)/src/misc/lv_fs.c  \
         $(LVGL_PATH)/src/misc/lv_ll.c  \
         $(LVGL_PATH)/src/misc/lv_log.c  \
         $(LVGL_PATH)/src/misc/lv_lru.c  \
         $(LVGL_PATH)/src/misc/lv_math.c  \
         $(LVGL_PATH)/src/misc/lv_palette.c  \
         $(LVGL_PATH)/src/misc/lv_profiler_builtin.c  \
         $(LVGL_PATH)/src/misc/lv_rb.c  \
         $(LVGL_PATH)/src/misc/lv_style.c  \
         $(LVGL_PATH)/src/misc/lv_style_gen.c  \
         $(LVGL_PATH)/src/misc/lv_templ.c  \
         $(LVGL_PATH)/src/misc/lv_text.c  \
         $(LVGL_PATH)/src/misc/lv_text_ap.c  \
         $(LVGL_PATH)/src/misc/lv_timer.c  \
         $(LVGL_PATH)/src/misc/lv_utils.c  \
         $(LVGL_PATH)/src/osal/lv_cmsis_rtos2.c  \
         $(LVGL_PATH)/src/osal/lv_freertos.c  \
         $(LVGL_PATH)/src/osal/lv_os_none.c  \
         $(LVGL_PATH)/src/osal/lv_pthread.c  \
         $(LVGL_PATH)/src/osal/lv_rtthread.c  \
         $(LVGL_PATH)/src/osal/lv_windows.c  \
         $(LVGL_PATH)/src/others/file_explorer/lv_file_explorer.c  \
         $(LVGL_PATH)/src/others/fragment/lv_fragment.c  \
         $(LVGL_PATH)/src/others/fragment/lv_fragment_manager.c  \
         $(LVGL_PATH)/src/others/gridnav/lv_gridnav.c  \
         $(LVGL_PATH)/src/others/ime/lv_ime_pinyin.c  \
         $(LVGL_PATH)/src/others/imgfont/lv_imgfont.c  \
         $(LVGL_PATH)/src/others/monkey/lv_monkey.c  \
         $(LVGL_PATH)/src/others/observer/lv_observer.c  \
         $(LVGL_PATH)/src/others/snapshot/lv_snapshot.c  \
         $(LVGL_PATH)/src/others/sysmon/lv_sysmon.c  \
         $(LVGL_PATH)/src/stdlib/builtin/lv_mem_core_builtin.c  \
         $(LVGL_PATH)/src/stdlib/builtin/lv_sprintf_builtin.c  \
         $(LVGL_PATH)/src/stdlib/builtin/lv_string_builtin.c  \
         $(LVGL_PATH)/src/stdlib/builtin/lv_tlsf.c  \
         $(LVGL_PATH)/src/stdlib/clib/lv_mem_core_clib.c  \
         $(LVGL_PATH)/src/stdlib/clib/lv_sprintf_clib.c  \
         $(LVGL_PATH)/src/stdlib/clib/lv_string_clib.c  \
         $(LVGL_PATH)/src/stdlib/lv_mem.c  \
         $(LVGL_PATH)/src/stdlib/micropython/lv_mem_core_micropython.c  \
         $(LVGL_PATH)/src/stdlib/rtthread/lv_mem_core_rtthread.c  \
         $(LVGL_PATH)/src/stdlib/rtthread/lv_sprintf_rtthread.c  \
         $(LVGL_PATH)/src/stdlib/rtthread/lv_string_rtthread.c  \
         $(LVGL_PATH)/src/themes/default/lv_theme_default.c  \
         $(LVGL_PATH)/src/themes/lv_theme.c  \
         $(LVGL_PATH)/src/themes/mono/lv_theme_mono.c  \
         $(LVGL_PATH)/src/themes/simple/lv_theme_simple.c  \
         $(LVGL_PATH)/src/tick/lv_tick.c  \
         $(LVGL_PATH)/src/widgets/animimage/lv_animimage.c  \
         $(LVGL_PATH)/src/widgets/arc/lv_arc.c  \
         $(LVGL_PATH)/src/widgets/bar/lv_bar.c  \
         $(LVGL_PATH)/src/widgets/button/lv_button.c  \
         $(LVGL_PATH)/src/widgets/buttonmatrix/lv_buttonmatrix.c  \
         $(LVGL_PATH)/src/widgets/calendar/lv_calendar.c  \
         $(LVGL_PATH)/src/widgets/calendar/lv_calendar_header_arrow.c  \
         $(LVGL_PATH)/src/widgets/calendar/lv_calendar_header_dropdown.c  \
         $(LVGL_PATH)/src/widgets/canvas/lv_canvas.c  \
         $(LVGL_PATH)/src/widgets/chart/lv_chart.c  \
         $(LVGL_PATH)/src/widgets/checkbox/lv_checkbox.c  \
         $(LVGL_PATH)/src/widgets/dropdown/lv_dropdown.c  \
         $(LVGL_PATH)/src/widgets/image/lv_image.c  \
         $(LVGL_PATH)/src/widgets/imagebutton/lv_imagebutton.c  \
         $(LVGL_PATH)/src/widgets/keyboard/lv_keyboard.c  \
         $(LVGL_PATH)/src/widgets/label/lv_label.c  \
         $(LVGL_PATH)/src/widgets/led/lv_led.c  \
         $(LVGL_PATH)/src/widgets/line/lv_line.c  \
         $(LVGL_PATH)/src/widgets/list/lv_list.c  \
         $(LVGL_PATH)/src/widgets/menu/lv_menu.c  \
         $(LVGL_PATH)/src/widgets/msgbox/lv_msgbox.c  \
         $(LVGL_PATH)/src/widgets/objx_templ/lv_objx_templ.c  \
         $(LVGL_PATH)/src/widgets/roller/lv_roller.c  \
         $(LVGL_PATH)/src/widgets/scale/lv_scale.c  \
         $(LVGL_PATH)/src/widgets/slider/lv_slider.c  \
         $(LVGL_PATH)/src/widgets/span/lv_span.c  \
         $(LVGL_PATH)/src/widgets/spinbox/lv_spinbox.c  \
         $(LVGL_PATH)/src/widgets/spinner/lv_spinner.c  \
         $(LVGL_PATH)/src/widgets/switch/lv_switch.c  \
         $(LVGL_PATH)/src/widgets/table/lv_table.c  \
         $(LVGL_PATH)/src/widgets/tabview/lv_tabview.c  \
         $(LVGL_PATH)/src/widgets/textarea/lv_textarea.c  \
         $(LVGL_PATH)/src/widgets/tileview/lv_tileview.c  \
         $(LVGL_PATH)/src/widgets/win/lv_win.c  \

#CSRCS += $(shell find $(LVGL_PATH)/demos -type f -name '*.c')
#CSRCS += $(shell find $(LVGL_PATH)/examples -type f -name '*.c')
#CXXEXT := .cpp
#CXXSRCS += $(shell find $(LVGL_PATH)/src/libs/thorvg -type f -name '*${CXXEXT}')

#AFLAGS += "-I$(LVGL_PATH)"
CFLAGS += "-I$(LVGL_PATH)"
CXXFLAGS += "-I$(LVGL_PATH)"
